# -*- coding: utf-8 -*-
"""DSAI_103 project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QywVEUGu8bMaTiCgx3h8FHphoVY4CK3q
"""

!pip install google-search-results
!pip install requests beautifulsoup4

import requests
from serpapi import GoogleScholarSearch
from serpapi import GoogleSearch
from bs4 import BeautifulSoup
import networkx as nx
import matplotlib.pyplot as plt

query=input("Enter your query:")

params={
    "q": query,
    "language":"en",
    "api_key":"5ef581b592c4ec7ad163673a1fde26b256ac37c18d2b9e9ee5655db49292481e"
}
search=GoogleScholarSearch(params)
results=search.get_dict()
org_res = results["organic_results"]
org_res[0]

res=results["organic_results"]
res[0]
main_topic=[]
main_topic.append(res[0]["title"])
main_topic

cited_data=[]
for i in range(len(res)):
  for key, value in res[0].items():
    if key=="inline_links":
      cited_data.append(value['cited_by']['cites_id'])
      print(value['cited_by']['cites_id'])
print(cited_data)

cited_data=[]

for key, value in res[0].items():
    if key=="inline_links":
      cited_data.append(value['cited_by']['cites_id'])
      print(value['cited_by']['cites_id'])
print(cited_data)

parameters={
    "cites": cited_data[0],
    "language":"en",
    "api_key":"5ef581b592c4ec7ad163673a1fde26b256ac37c18d2b9e9ee5655db49292481e"
}
search=GoogleScholarSearch(params)
results=search.get_dict()
org_res = results["organic_results"]
org_res

cited_titles=[]
for i in range (len(org_res)):
  cited_titles.append(org_res[i]["title"])
cited_titles
#print(org_res[i]["title"])

G=nx.DiGraph()
G.add_node(main_topic[0])
G.nodes()
for i in range (len(cited_titles)):
  G.add_node(cited_titles[i])
  G.add_edge(main_topic[0],cited_titles[i])

plt.figure(figsize=(15,10))
node_size=7000
nx.draw(G,with_labels=True,node_size=node_size)
plt.show()

res=results["organic_results"]
res[0]

for i in range (len(res)):
  print(res[i]["link"])

for i in range (len(res)):
  if("cited_by" in res[i]["inline_links"]):
    print(res[i]["inline_links"]["cited_by"]["total"])

for i in range (len(res)):
  print(res[i]["title"])

first_result = res[0]
if("cited_by" in res[0]["inline_links"]):
     print(res[0]["link"])
     print(res[0]["inline_links"]["cited_by"]["total"])
     print(res[0]["title"])

# query=input("Enter your query:")
# params={
#     "q": query,
#     "language":"en",
#     "api_key":"5ef581b592c4ec7ad163673a1fde26b256ac37c18d2b9e9ee5655db49292481e"
# }
# search=GoogleScholarSearch(params)
# results=search.get_dict()
# print(results)
# res=results["organic_results"]
# print(res)
# for i in range (len(res)):
#   print(res[i]["link"])

# for i in range (len(res)):
#   if("cited_by" in res[i]["inline_links"]):
#     print(res[i]["inline_links"]["cited_by"]["total"])

#  for i in range (len(res)):
#    print(res[i]["title"])